"""New_column

Revision ID: 1655102345fa
Revises: ae29fd0d46e0
Create Date: 2024-06-25 23:11:45.188431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1655102345fa'
down_revision: Union[str, None] = 'ae29fd0d46e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_first_time', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_first_time')
    # ### end Alembic commands ###
