services:
  pg:
    image: postgres:16-alpine
    env_file:
      - ./.pg.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: on-failure
    depends_on:
      - pg
    command: sh -c "sleep 3 && make migrate && python run.py"

volumes:
  pgdata:
