version: '3.9'
services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./.pg.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    restart: on-failure
    depends_on:
      - db
    command: sh -c "sleep 5 && python bot/run.py"

volumes:
  pgdata:
